<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript">

    /*
        1.Promise.all([p1,p2,....]) 用于将多个Promise实例，包装成一个新的Promise实例;
          返回的实例就是普通Promise; 参数为衣蛾数组;

        2.数组里面可以是Promise对象，也可以是别的值，只有Promise会等待状态改变;

        3.当所有的子Promise都完成，该Promise 完成，返回值是全部值的数组;

        4.有任何一个失败的,该Promise 失败，返回的值是第一个失败的子Promise 的结果;

     */ 

     console.log('start');

     Promise.all([1,2,3])
     .then(all =>{
        // all 中都不是Promise 对象 所以直接返回;
        console.log('1',all);
        return Promise.all([function(){
            console.log('xx');
        },'xx',false])
     })
     .then(all=>{
        // 上面 all中传了函数 也不是Promise对象所以直接就输出了;
        console.log('2',all);
        let p1 = new Promise(resolve=>{
            setTimeout(()=>{
                resolve('I,m P1');
            },2000)
        });
        let p2 = new Promise(resolve=>{
            setTimeout(()=>{
                resolve('I,m p2')
            },1000)
        })
        return Promise.all([p1,p2]);

     })
     .then( all=>{
        console.log('3:',all);  // 等待年两秒后输出结果;
        let p1  =new Promise(resolve=>{
            setTimeout(()=>{
                resolve('I,m p1');
            },1500)
        });
        let p2 =new Promise((resolve,reject)=>{
            setTimeout(()=>{
                reject('I,m p2');
            },1000)
        })
        let p3 = new Promise((resolve,reject)=>{
            setTimeout(()=>{
                reject('I,m p3')
            },3000)
        });
        return Promise.all([p1,p2,p3]);
     })
     .then( all =>{
        console.log('all',all);
     })
     .catch(err =>{
        console.log('catch:',err); // 捕获了p2中的错误; 所以返回 I,m p2;
     })




    </script>
</body>
</html>